server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: upload-service
          uri: lb://UPLOAD-SERVICE
          predicates:
            - Path=/api/uploads/**
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/videos/**, /api/stream/**
        - id: notification-service
          uri: lb:ws://NOTIFICATION-SERVICE
          predicates:
            - Path=/ws/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
